import './globals.css'
import type { Metadata } from 'next'
import MyApp from './app'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <MyApp>
          {children}
        </MyApp>
      </body>
    </html>
  )
}
